import TanstackQueryProvider from '@meato/packages/frontend/ui/components/TanstackQueryProvider';
import './global.css';

export const metadata = {
  title: 'Welcome to vendor-ui',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
     <html lang="en">
      <body className='text-white'>
        <TanstackQueryProvider>
          {children}
        </TanstackQueryProvider>
      </body>
    </html>
  );
}