// import TanstackQueryProvider from 'packages/frontend/ui/src/components/TanstackQueryProvider';
// import './global.css';
// import { Inter, Poppins } from 'next/font/google';

// // Configure Inter font (great for body text)
// const inter = Inter({
//   subsets: ['latin'],
//   display: 'swap',
//   variable: '--font-inter',
// });

// // Configure Poppins font (great for headings)
// const poppins = Poppins({
//   weight: ['400', '500', '600', '700'],
//   subsets: ['latin'],
//   display: 'swap',
//   variable: '--font-poppins',
// });

// export const metadata = {
//   title: 'Welcome to user-ui',
//   description: 'Generated by create-nx-workspace',
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en" className={`${inter.variable} ${poppins.variable}`}>
//       <body className={inter.className}>
//         <TanstackQueryProvider>
//           {children}
//         </TanstackQueryProvider>
//       </body>
//     </html>
//   );
// }
// import TanstackQueryProvider from '@meato/packages/frontend/ui/components/TanstackQueryProvider';
import TanstackQueryProvider from '@meato/packages/frontend/ui/components/TanstackQueryProvider';
import './global.css';

export const metadata = {
  title: 'Welcome to manager-ui',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className='dark'>
      <body className='text-white'>
        <TanstackQueryProvider>
          {children}
        </TanstackQueryProvider>
      </body>
    </html>
  );
}
