import TanstackQueryProvider from '@meato/packages/frontend/ui/components/TanstackQueryProvider';
import './global.css';
export const metadata = {
  title: 'Welcome to admin-ui',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <TanstackQueryProvider>
          <main className='dark'>
            {children}
          </main>
        </TanstackQueryProvider>
      </body>
    </html>
  );
}