type VendorDataType = {
    id: number,
    email: string,
    username: string,
    phone: string,
    shop_address: string,
    shop_name: string,
    gst_number: string,
    shop_city: string,
    shop_state: string,
    shop_pinCode: string,
    bank_account: string,
    ifsc_code: string,
    fssai_license: string,
    commission_rate?: string,
    status: string,
    oreders?: string,
    rejected_orderds?: number,
    createdAt: string,
    updatedAt?: string,
}